packages:
  # all packages in direct subdirs of packages/
  - 'apps/**'
  # all packages in subdirs of components/
  # - "shared/**"
  # exclude packages that are inside test directories
  - '!**/test/**'
